import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0c0e18",
        "on-secondary": "#2d2f45",
        "on-secondary-fixed-variant": "#43455c",
        "on-error": "#690005",
        "tertiary": "#9bd9ff",
        "tertiary-container": "#3ac2ff",
        "secondary": "#c4c4e0",
        "surface-bright": "#373845",
        "on-background": "#e1e1f2",
        "inverse-primary": "#835500",
        "on-primary-fixed-variant": "#633f00",
        "on-tertiary-fixed": "#001e2c",
        "surface": "#11131e",
        "surface-dim": "#11131e",
        "surface-variant": "#323440",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#191b26",
        "primary-fixed-dim": "#ffb955",
        "outline-variant": "#524534",
        "on-secondary-fixed": "#181a2f",
        "outline": "#9f8e7a",
        "surface-tint": "#ffb955",
        "secondary-fixed-dim": "#c4c4e0",
        "on-surface-variant": "#d7c3ae",
        "surface-container-highest": "#323440",
        "background": "#11131e",
        "inverse-on-surface": "#2e303c",
        "on-surface": "#e1e1f2",
        "on-primary": "#452b00",
        "primary-container": "#f5a623",
        "on-tertiary-container": "#004d6a",
        "on-tertiary": "#00344a",
        "on-tertiary-fixed-variant": "#004c69",
        "on-primary-fixed": "#291800",
        "surface-container": "#1d1f2b",
        "surface-container-high": "#272935",
        "secondary-fixed": "#e0e0fd",
        "inverse-surface": "#e1e1f2",
        "primary-fixed": "#ffddb4",
        "on-secondary-container": "#b2b3ce",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#7cd0ff",
        "secondary-container": "#43455c",
        "on-primary-container": "#644000",
        "primary": "#ffc880",
        "tertiary-fixed": "#c4e7ff",
        "error-container": "#93000a",
      },
      fontFamily: {
        headline: ["Epilogue", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
